/* eslint-disable */
// GENERATED by scripts/gen-types.mjs from `pagelamp schema` — DO NOT EDIT.
// Source of truth: crates/pagelamp-app/src/lib.rs, crates/pagelamp-core/src/{model,views}.rs

/**
 * Whether an AI app may read a course's material TEXT over MCP (docs/ARCHITECTURE.md §3
 * rule 8). Computed from `Course.ai_policy` and `Course.ai_access`, never stored.
 * Structure (titles, kinds, dates, weeks, URLs, counts), deadlines and study plans are
 * always available; only material text is withheld.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AiMaterialsState".
 */
export type AiMaterialsState = "readable" | "turned_off" | "withheld_by_policy";
/**
 * How the student is allowed to use generative AI in a course. Defaults to `Unknown`,
 * which consumers must treat like `LearningAid` for explanations but must never treat as
 * permission to produce graded work (UofT default: GenAI not permitted unless allowed).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AiPolicy".
 */
export type AiPolicy =
  "unknown" | "prohibited" | "learning_aid" | "allowed_with_citation" | "unrestricted";
/**
 * What kind of failure happened; UIs branch on this, never on `message`.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AppErrorKind".
 */
export type AppErrorKind =
  "auth" | "network" | "invalid" | "not_found" | "ambiguous" | "busy" | "internal";
/**
 * Where course data comes from.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SourceKind".
 */
export type SourceKind = "canvas" | "folder" | "ical";
/**
 * Why a source failed to sync. Persisted as `sources.last_error_kind`.
 *
 * Classification: Canvas 401 / invalid token and feed-URL 401/403 → `AuthExpiredOrRevoked`;
 * DNS/TLS/timeout/connection refused → `Network`; missing folder, feed 404 or Canvas host 404
 * → `NotFound`; Canvas throttling still failing after all retries → `RateLimited`.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SourceErrorKind".
 */
export type SourceErrorKind =
  "auth_expired_or_revoked" | "network" | "not_found" | "rate_limited" | "other";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "MaterialKind".
 */
export type MaterialKind = ("announcement" | "syllabus") | "file" | "page" | "external_link";
/**
 * Whether we have searchable text for a material.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "TextStatus".
 */
export type TextStatus = "pending" | "ok" | "unsupported" | "not_downloaded" | "error";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "Confidence".
 */
export type Confidence = "high" | "medium" | "low";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "EventKind".
 */
export type EventKind =
  ("assignment_due" | "quiz_due" | "exam" | "other") | "class_event" | "planner_item";
/**
 * Which kind of process writes the log (selects the file name).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "ProcessKind".
 */
export type ProcessKind = "app" | "mcp";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "McpClient".
 */
export type McpClient = "claude_desktop" | "claude_code" | "codex" | "generic";
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "InstallKind".
 */
export type InstallKind = "json_snippet" | "shell_command" | "toml_snippet";
/**
 * Stable codes for `McpClientConfig.notes` (one code per note).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "McpNoteCode".
 */
export type McpNoteCode =
  | "works_on_all_claude_plans"
  | "admins_may_disable_extensions"
  | "needs_paid_claude_plan"
  | "codex_config_shared_with_chatgpt_desktop"
  | "codex_plus_and_edu_documented"
  | "free_go_undocumented"
  | "restart_client_after_change"
  | "custom_data_dir"
  | "generic_stdio_client";
/**
 * Progress stream of a sync run (desktop forwards these through a `tauri::ipc::Channel`).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SyncEvent".
 */
export type SyncEvent =
  | {
      label: string;
      source_id: string;
      type: "source_started";
    }
  | {
      current?: number | null;
      message: string;
      source_id: string;
      total?: number | null;
      type: "progress";
    }
  | {
      message: string;
      source_id: string;
      type: "warning";
    }
  | {
      error?: string | null;
      error_kind?: SourceErrorKind | null;
      ok: boolean;
      source_id: string;
      type: "source_finished";
    };
/**
 * Origin of a course's effective term dates.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "TermSource".
 */
export type TermSource = "user" | "synced" | "none";
/**
 * Why `WeekMaterials.note` is set.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "WeekNoteKind".
 */
export type WeekNoteKind = "current_week_unknown" | "outside_term" | "no_materials_this_week";

/**
 * Container whose only purpose is to pull every facade type into one schema document
 * (`$defs`), so json-schema-to-typescript emits one TS file with all of them.
 */
export interface PageLampAppTypes {
  ai_materials_state: AiMaterialsState;
  ai_policy: AiPolicy;
  app_error: AppError;
  app_status: AppStatus;
  course_overview: CourseOverview;
  course_summary: CourseSummary;
  course_sync_summary: CourseSyncSummary;
  crash_report: CrashReport;
  deadline: Deadline;
  doctor_report: DoctorReport;
  mcp_client_config: McpClientConfig;
  process_kind: ProcessKind;
  search_hit: SearchHit;
  source_error_kind: SourceErrorKind;
  source_record: SourceRecord;
  source_sync_result: SourceSyncResult;
  stored_study_plan: StoredStudyPlan;
  sync_event: SyncEvent;
  sync_request: SyncRequest;
  sync_summary: SyncSummary;
  term_source: TermSource;
  week_materials: WeekMaterials;
}
/**
 * Error returned by every facade method. Serialised as-is by the Tauri commands.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AppError".
 */
export interface AppError {
  kind: AppErrorKind;
  /**
   * User-presentable; never contains a secret.
   */
  message: string;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "AppStatus".
 */
export interface AppStatus {
  counts: StoreCounts;
  data_dir: string;
  db_path: string;
  /**
   * Most recent successful sync over all sources.
   */
  last_synced_at?: string | null;
  sources: SourceRecord[];
  /**
   * True while any process holds `sync.lock`.
   */
  sync_in_progress: boolean;
  /**
   * Version of this PageLamp build.
   */
  version: string;
}
/**
 * Row counts for status screens / `sync_status`.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "StoreCounts".
 */
export interface StoreCounts {
  chunks: number;
  /**
   * Visible (not hidden) courses.
   */
  courses: number;
  events: number;
  hidden_courses: number;
  /**
   * Materials with text_status = ok and at least one chunk.
   */
  indexed_materials: number;
  materials: number;
  modules: number;
  study_plans: number;
}
/**
 * A configured data source. Secrets (Canvas token, calendar-feed URL) are NOT stored here;
 * they live in the OS keychain keyed by `id` (see `secrets`).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SourceRecord".
 */
export interface SourceRecord {
  /**
   * Non-secret configuration. Canvas: `{"base_url": "https://lms.example.edu"}`.
   * Folder: `{"path": "/Users/me/Courses", "term_start": "2026-09-08"?}`.
   * Ical: `{}` (the URL itself is a secret).
   */
  config: {
    [k: string]: unknown;
  };
  /**
   * e.g. `canvas:lms.example.edu`, `folder:3f2a…`, `ical:9b1c…`
   */
  id: string;
  kind: SourceKind;
  /**
   * Human label shown in status output, e.g. "Quercus" or "~/Courses".
   */
  label: string;
  /**
   * Error message of the most recent failed sync, cleared on success. Never contains secrets.
   */
  last_error?: string | null;
  /**
   * Machine-readable class of `last_error` (UIs branch on this, never on the message).
   */
  last_error_kind?: SourceErrorKind | null;
  last_synced_at?: string | null;
}
/**
 * Everything needed to answer "what's going on in this course right now".
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseOverview".
 */
export interface CourseOverview {
  /**
   * Effective AI access to this course's material text (`Course::ai_materials`).
   */
  ai_materials: "readable" | "turned_off" | "withheld_by_policy";
  course: Course;
  current_modules: Module[];
  last_synced_at?: string | null;
  /**
   * Announcements posted in the last `RECENT_DAYS` days, newest first (titles + ids only).
   */
  recent_announcements: MaterialView[];
  /**
   * Materials published in the last `RECENT_DAYS` days, newest first (announcements excluded).
   */
  recent_materials: MaterialView[];
  source_label: string;
  timeline: CourseTimeline;
  /**
   * Deadlines due in the next `UPCOMING_DAYS` days, soonest first.
   */
  upcoming_deadlines: Deadline[];
}
/**
 * A course as read back from the store: synced fields + user overrides resolved.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "Course".
 */
export interface Course {
  /**
   * The student's switch "Let my AI app read this course's materials" (default on).
   * Use `ai_materials()` for the effective state — a `prohibited` policy wins over it.
   */
  ai_access: boolean;
  ai_policy: AiPolicy;
  /**
   * Free text the student recorded about the policy (e.g. a quote from the syllabus).
   */
  ai_policy_note?: string | null;
  code?: string | null;
  /**
   * False when the LMS no longer lists the course as active (e.g. the term ended). Such
   * courses are kept with all their data; only the student removes them.
   */
  enrollment_active: boolean;
  external_id: string;
  hidden: boolean;
  id: string;
  name: string;
  source_id: string;
  term_end?: string | null;
  /**
   * Where the effective term dates come from (`set_course_term(None, None)` clears the
   * user override and falls back to the synced dates).
   */
  term_source: "user" | "synced" | "none";
  /**
   * Effective term start = user override if set, else synced value.
   */
  term_start?: string | null;
  updated_at: string;
  url?: string | null;
}
/**
 * A unit of course structure (Canvas module, or a sub-folder like "Week 3").
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "Module".
 */
export interface Module {
  course_id: string;
  id: string;
  name: string;
  position?: number | null;
  unlock_at?: string | null;
  /**
   * Week number parsed from the name ("Week 3", "W03"), if any.
   */
  week_hint?: number | null;
}
/**
 * A material as listed in views (no text; use `read_material` for text).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "MaterialView".
 */
export interface MaterialView {
  /**
   * Number of text chunks (pages/slides/sections) available via `read_material`.
   */
  chunk_count: number;
  course_id: string;
  id: string;
  kind: MaterialKind;
  module_id?: string | null;
  module_name?: string | null;
  published_at?: string | null;
  text_error?: string | null;
  text_status: TextStatus;
  title: string;
  /**
   * Where the student can open the original (LMS URL or `file://` URL).
   */
  url?: string | null;
  week_hint?: number | null;
}
/**
 * "Where is this course right now", with the evidence that led to the conclusion so an AI
 * client can explain (and a student can correct) it.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseTimeline".
 */
export interface CourseTimeline {
  as_of: string;
  confidence: Confidence;
  /**
   * Modules considered current (most recently unlocked / matching current week).
   */
  current_module_ids: string[];
  current_week?: number | null;
  /**
   * Human-readable reasons, e.g. "module 'Week 4: Backprop' unlocked 2026-09-29".
   */
  evidence: string[];
  /**
   * True when the date is outside the known term (before start / after end).
   */
  outside_term: boolean;
}
/**
 * A deadline/event enriched with its course's code and name (all `Event` fields are
 * flattened into the same JSON object).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "Deadline".
 */
export interface Deadline {
  course_code?: string | null;
  course_id?: string | null;
  course_name?: string | null;
  due_at?: string | null;
  ends_at?: string | null;
  id: string;
  kind: EventKind;
  source_id: string;
  starts_at?: string | null;
  title: string;
  updated_at: string;
  url?: string | null;
}
/**
 * One row of the course list ("where is each course this week").
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseSummary".
 */
export interface CourseSummary {
  /**
   * Effective AI access to this course's material text (`Course::ai_materials`).
   */
  ai_materials: "readable" | "turned_off" | "withheld_by_policy";
  counts: CourseCounts;
  course: Course;
  /**
   * When that source last synced successfully (data freshness).
   */
  last_synced_at?: string | null;
  next_deadline?: Deadline | null;
  /**
   * Label of the source this course came from (e.g. "Quercus", "~/Courses").
   */
  source_label: string;
  timeline: CourseTimeline;
}
/**
 * Per-course counts shown in course lists.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseCounts".
 */
export interface CourseCounts {
  /**
   * Materials whose text the student's AI app can read: indexed materials, but 0 unless
   * the course's `ai_materials` state is `readable`.
   */
  indexed_materials: number;
  materials: number;
  modules: number;
  /**
   * Deadlines due in the next `UPCOMING_DAYS` days.
   */
  upcoming_deadlines: number;
}
/**
 * What one sync did for one course (the `pagelamp sync` summary; desktop status screens).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CourseSyncSummary".
 */
export interface CourseSyncSummary {
  /**
   * Course code, or name when it has no code.
   */
  course: string;
  /**
   * Deadlines/events read for this course.
   */
  events: number;
  /**
   * Files listed (downloaded or not).
   */
  files: number;
  modules: number;
  pages: number;
  warnings: number;
}
/**
 * The most recent crash (`logs/last-crash.json`), until cleared.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "CrashReport".
 */
export interface CrashReport {
  /**
   * `file.rs:line:column` of the panic.
   */
  location?: string | null;
  /**
   * Redacted, at most 500 characters.
   */
  message: string;
  process: ProcessKind;
  time: string;
  version: string;
}
/**
 * `pagelamp doctor`: the facts a maintainer needs to help, and nothing personal.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "DoctorReport".
 */
export interface DoctorReport {
  arch: string;
  courses: number;
  /**
   * With the home directory shortened to `~`.
   */
  data_dir: string;
  /**
   * Why the database could not be read (then the counts are 0).
   */
  database_error?: string | null;
  events: number;
  hidden_courses: number;
  keychain_available: boolean;
  keychain_error?: string | null;
  last_crash?: CrashReport | null;
  logs_dir: string;
  materials: number;
  mcp_clients: McpClientPresence;
  os: string;
  schema_version?: number | null;
  sources: DoctorSource[];
  version: string;
}
/**
 * Whether each AI app's config has a PageLamp entry (presence only; nothing else is read
 * out of those files).
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "McpClientPresence".
 */
export interface McpClientPresence {
  claude_code: boolean;
  claude_desktop: boolean;
  codex: boolean;
}
/**
 * A source as `doctor` shows it: no ids, URLs or labels.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "DoctorSource".
 */
export interface DoctorSource {
  kind: SourceKind;
  last_error_kind?: SourceErrorKind | null;
  last_synced_at?: string | null;
  /**
   * The last sync succeeded (false when it failed or never ran).
   */
  ok: boolean;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "McpClientConfig".
 */
export interface McpClientConfig {
  client: McpClient;
  /**
   * Where the snippet goes, e.g. "~/Library/Application Support/Claude/claude_desktop_config.json".
   */
  config_path_hint?: string | null;
  /**
   * The snippet / command to copy.
   */
  content: string;
  install_kind: InstallKind;
  launch: McpLaunch;
  /**
   * Machine-readable code of each entry of `notes` (same length, same order) so UIs can
   * localise.
   */
  note_codes: McpNoteCode[];
  /**
   * Facts the student should know (plan availability, restart the app, …), in English.
   */
  notes: string[];
  /**
   * e.g. "Claude Desktop".
   */
  title: string;
}
/**
 * How an MCP client launches the server — the single source every snippet (and, later,
 * a `.mcpb` Desktop Extension manifest) is generated from.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "McpLaunch".
 */
export interface McpLaunch {
  args: string[];
  /**
   * Absolute path of the `pagelamp` binary.
   */
  command: string;
  /**
   * Extra environment (only `PAGELAMP_HOME` when the data dir is not the default).
   */
  env: {
    [k: string]: string;
  };
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SearchHit".
 */
export interface SearchHit {
  chunk_ord: number;
  course_code?: string | null;
  course_id: string;
  locator?: string | null;
  material_id: string;
  material_title: string;
  /**
   * Lower is better (FTS5 bm25).
   */
  score: number;
  /**
   * Short excerpt around the match (FTS5 snippet), with matches wrapped in «».
   */
  snippet: string;
  url?: string | null;
  week_hint?: number | null;
}
/**
 * Outcome of syncing one source. A failing source is `ok: false` (not an `Err`), so
 * `sync_all` can report partial success.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SourceSyncResult".
 */
export interface SourceSyncResult {
  /**
   * Per-course details (Canvas; empty for other sources).
   */
  course_summaries: CourseSyncSummary[];
  courses: number;
  error?: string | null;
  error_kind?: SourceErrorKind | null;
  events: number;
  files_downloaded: number;
  files_indexed: number;
  finished_at: string;
  kind: SourceKind;
  label: string;
  materials: number;
  modules: number;
  ok: boolean;
  /**
   * HTTP requests made (Canvas; None for other sources).
   */
  requests?: number | null;
  source_id: string;
  started_at: string;
  warnings: string[];
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "StoredStudyPlan".
 */
export interface StoredStudyPlan {
  created_at: string;
  id: number;
  plan: StudyPlan;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "StudyPlan".
 */
export interface StudyPlan {
  horizon_end: string;
  horizon_start: string;
  items: StudyPlanItem[];
  notes?: string | null;
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "StudyPlanItem".
 */
export interface StudyPlanItem {
  /**
   * Course id (or code) this task belongs to, if any.
   */
  course_id?: string | null;
  date: string;
  description?: string | null;
  done?: boolean;
  /**
   * Materials to study for this item (ids from `week_materials` / `search_materials`).
   */
  material_ids?: string[];
  minutes?: number | null;
  title: string;
}
/**
 * Options for a sync run. All fields have defaults, so `{}` is a valid request.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SyncRequest".
 */
export interface SyncRequest {
  /**
   * Download LMS (Canvas) files and index their text. Default FALSE: downloading a file
   * through Canvas counts as viewing it (it can complete "must view" module requirements
   * and shows up in instructor analytics), so files are listed as `not_downloaded` unless
   * the student explicitly asks — see `App::download_course_files`. Folder sources are
   * local and always indexed.
   */
  download_files?: boolean;
  /**
   * Skip LMS files larger than this many megabytes.
   */
  max_file_mb?: number;
  /**
   * Only sync these courses (ids or codes); empty = all.
   */
  only_courses?: string[];
}
/**
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "SyncSummary".
 */
export interface SyncSummary {
  finished_at: string;
  /**
   * True when every source synced successfully.
   */
  ok: boolean;
  results: SourceSyncResult[];
  started_at: string;
}
/**
 * Materials of one teaching week.
 *
 * This interface was referenced by `PageLampAppTypes`'s JSON-Schema
 * via the `definition` "WeekMaterials".
 */
export interface WeekMaterials {
  /**
   * Effective AI access to this course's material text (`Course::ai_materials`).
   */
  ai_materials: "readable" | "turned_off" | "withheld_by_policy";
  /**
   * Every week that has at least one module or material (plus the current week), ascending —
   * drives the ‹ Week › switcher.
   */
  available_weeks: number[];
  course: Course;
  materials: MaterialView[];
  /**
   * Modules belonging to this week.
   */
  modules: Module[];
  /**
   * Explains any fallback, e.g. "current week unknown — showing materials of the last 14 days".
   */
  note?: string | null;
  /**
   * Machine-readable class of `note` (UIs localise from this; `note` stays English).
   */
  note_kind?: WeekNoteKind | null;
  /**
   * The week the caller asked for (None = "current week").
   */
  requested_week?: number | null;
  timeline: CourseTimeline;
  /**
   * The week actually shown (None when no week could be determined; see `note`).
   */
  week?: number | null;
}
