#!/usr/bin/env node
// i18next JSON → Apple Localizable.strings / .stringsdict for the native Mac app (spec §7.3).
// Zero dependencies: Node ≥ 24 and node: built-ins only. Output is deterministic.
//
//   node apps/macos/scripts/gen-strings.mjs            write the generated files
//   node apps/macos/scripts/gen-strings.mjs --check    exit 1 if a generated file is missing or stale (CI)
//   options: --root <dir>   repository root (default: three levels up)
//            --brand <id>   brand whose productName replaces {{product}} (default: "default")
//
// Sources, one string source for Tauri and the Mac:
//   apps/desktop/src/i18n/locales/{en,zh-CN}/<ns>.json   → keys "<ns>.<path>"
//   apps/macos/Localization/<name>.{en,zh-CN}.json        → keys "mac.<path>" (every fragment merges
//                                                            into mac.*; a key in two fragments is an error)
// Outputs:
//   apps/macos/Sources/PageLamp/Resources/{en,zh-Hans}.lproj/Localizable.strings    plain strings
//   apps/macos/Sources/PageLamp/Resources/{en,zh-Hans}.lproj/Localizable.stringsdict i18next _one/_other plurals
//   apps/macos/Sources/PageLamp/Generated/L10nKeys.swift                             every key + argument names
//
// Rules: en and zh-CN must have the same keys and the same {{placeholders}} per key. {{product}} is
// replaced by the brand's productName. Every other {{name}} becomes a positional %N$@, numbered by
// first appearance in English and used with the same N in every language; a plural's {{count}} is
// %N$ld. "%" is escaped as "%%" in strings that take arguments.

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = resolve(SCRIPT_DIR, "..", "..", "..");
export const PATHS = Object.freeze({
  locales: "apps/desktop/src/i18n/locales",
  fragments: "apps/macos/Localization",
  brands: "apps/desktop/src/brand/brands",
  resources: "apps/macos/Sources/PageLamp/Resources",
  keys: "apps/macos/Sources/PageLamp/Generated/L10nKeys.swift",
});
/** i18next language → Apple localization, with its CLDR plural categories ("zero" is always allowed). */
export const LANGUAGES = Object.freeze([
  { source: "en", apple: "en", plurals: ["one", "other"] },
  { source: "zh-CN", apple: "zh-Hans", plurals: ["other"] },
]);
const PLURAL_ORDER = ["zero", "one", "two", "few", "many", "other"];
const PLURAL_SUFFIX = /_(zero|one|two|few|many|other)$/;
const PLACEHOLDER = /\{\{\s*([A-Za-z_]\w*)\s*\}\}/g;
const MAC_PREFIX = "mac";
const GENERATED_BY = "Generated by apps/macos/scripts/gen-strings.mjs. Do not edit.";

export class StringsError extends Error {}
const fail = (msg) => {
  throw new StringsError(msg);
};
const isObj = (v) => v !== null && typeof v === "object" && !Array.isArray(v);
const byCodePoint = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

// ───────────────────────────── reading ─────────────────────────────

/** Nested i18next JSON → [["a.b.c", "text"], …] in file order. Values must be strings. */
export function flattenMessages(node, prefix, where) {
  if (!isObj(node)) fail(`${where}: expected an object at ${prefix || "the top level"}`);
  const out = [];
  for (const [k, v] of Object.entries(node)) {
    if (k.includes(".")) fail(`${where}: key "${k}" contains "." (i18next uses it as the separator)`);
    const key = prefix ? `${prefix}.${k}` : k;
    if (typeof v === "string") out.push([key, v]);
    else if (isObj(v)) out.push(...flattenMessages(v, key, where));
    else fail(`${where}: ${key} must be a string or an object, got ${Array.isArray(v) ? "an array" : typeof v}`);
  }
  return out;
}

const readJson = (file) => {
  try {
    return JSON.parse(readFileSync(file, "utf8"));
  } catch (e) {
    fail(`${file}: ${e.message}`);
  }
};

/** { en: Map(key → text), "zh-CN": Map } from the shared i18next namespaces. */
export function loadShared(root) {
  const dir = join(root, PATHS.locales);
  const out = {};
  let namespaces;
  for (const { source } of LANGUAGES) {
    const files = readdirSync(join(dir, source)).filter((f) => f.endsWith(".json")).sort(byCodePoint);
    const ns = files.map((f) => f.slice(0, -".json".length));
    if (ns.includes(MAC_PREFIX)) fail(`${PATHS.locales}/${source}/${MAC_PREFIX}.json: the "${MAC_PREFIX}" namespace is reserved for apps/macos/Localization`);
    if (namespaces && ns.join() !== namespaces.join()) fail(`${PATHS.locales}: ${source} has namespaces [${ns}], expected [${namespaces}]`);
    namespaces = ns;
    const map = new Map();
    for (const f of files) {
      const where = `${PATHS.locales}/${source}/${f}`;
      for (const [k, v] of flattenMessages(readJson(join(dir, source, f)), f.slice(0, -".json".length), where)) map.set(k, v);
    }
    out[source] = map;
  }
  return out;
}

/** Mac fragments: every <name>.en.json needs a <name>.zh-CN.json; all merge under "mac.". */
export function loadFragments(root) {
  const dir = join(root, PATHS.fragments);
  const files = existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith(".json")).sort(byCodePoint) : [];
  const out = Object.fromEntries(LANGUAGES.map((l) => [l.source, new Map()]));
  const owner = Object.fromEntries(LANGUAGES.map((l) => [l.source, new Map()]));
  const names = new Map(LANGUAGES.map((l) => [l.source, new Set()]));
  for (const f of files) {
    const lang = LANGUAGES.find((l) => f.endsWith(`.${l.source}.json`));
    if (!lang) fail(`${PATHS.fragments}/${f}: fragment names end in ${LANGUAGES.map((l) => `.${l.source}.json`).join(" or ")}`);
    names.get(lang.source).add(f.slice(0, -`.${lang.source}.json`.length));
    const where = `${PATHS.fragments}/${f}`;
    for (const [k, v] of flattenMessages(readJson(join(dir, f)), MAC_PREFIX, where)) {
      const prev = owner[lang.source].get(k);
      if (prev) fail(`${k} is defined in both ${prev} and ${where}`);
      owner[lang.source].set(k, where);
      out[lang.source].set(k, v);
    }
  }
  const [first, ...rest] = LANGUAGES;
  for (const l of rest) {
    const a = [...names.get(first.source)].sort(byCodePoint).join();
    const b = [...names.get(l.source)].sort(byCodePoint).join();
    if (a !== b) fail(`${PATHS.fragments}: fragments differ between ${first.source} [${a}] and ${l.source} [${b}]`);
  }
  return out;
}

/** productName from apps/desktop/src/brand/brands/<id>.ts (a plain string literal). */
export function loadProductName(root, brand = "default") {
  const file = join(root, PATHS.brands, `${brand}.ts`);
  const m = /\bproductName\s*:\s*(["'])((?:(?!\1)[^\\\n])+)\1/.exec(readFileSync(file, "utf8"));
  return m?.[2] ?? fail(`${file}: no productName string literal`);
}

// ───────────────────────────── the catalog ─────────────────────────────

const placeholders = (text) => [...text.matchAll(PLACEHOLDER)].map((m) => m[1]);

function checkSyntax(key, lang, text) {
  if (/\$t\(/.test(text)) fail(`${lang} ${key}: i18next nesting $t(…) is not supported`);
  const leftover = text.replace(PLACEHOLDER, "");
  if (/\{\{|\}\}/.test(leftover)) fail(`${lang} ${key}: unsupported interpolation in "${text}" (only {{name}})`);
}

/**
 * Builds the catalog from { en: Map, "zh-CN": Map } (shared + mac merged) and checks parity.
 * Returns entries sorted by key: { key, plural, args, texts: { en: string | {category: string} } }.
 */
export function buildCatalog(messages, productName) {
  const [en, ...others] = LANGUAGES.map((l) => l.source);
  const sub = (s) => s.replace(/\{\{\s*product\s*\}\}/g, productName);
  const keysOf = (lang) => new Set(messages[lang].keys());
  for (const lang of others) {
    const a = keysOf(en);
    const b = keysOf(lang);
    const missing = [...a].filter((k) => !b.has(k)).sort(byCodePoint);
    const extra = [...b].filter((k) => !a.has(k)).sort(byCodePoint);
    if (missing.length || extra.length)
      fail(
        [
          `${lang} must have exactly the keys of ${en}.`,
          missing.length ? `  missing in ${lang}: ${missing.slice(0, 20).join(", ")}${missing.length > 20 ? ", …" : ""}` : "",
          extra.length ? `  only in ${lang}: ${extra.slice(0, 20).join(", ")}${extra.length > 20 ? ", …" : ""}` : "",
        ]
          .filter(Boolean)
          .join("\n"),
      );
  }
  for (const [lang, map] of Object.entries(messages)) for (const [k, v] of map) checkSyntax(k, lang, v);
  for (const lang of others)
    for (const [k, v] of messages[en]) {
      const a = [...new Set(placeholders(sub(v)))].sort(byCodePoint).join(", ");
      const b = [...new Set(placeholders(sub(messages[lang].get(k))))].sort(byCodePoint).join(", ");
      if (a !== b) fail(`${lang} ${k} uses {{${b}}} but ${en} uses {{${a}}}`);
    }

  // group plural forms
  const groups = new Map(); // key → { plural, forms: Map(category → key) }
  for (const k of messages[en].keys()) {
    const m = PLURAL_SUFFIX.exec(k);
    const base = m ? k.slice(0, -m[0].length) : k;
    if (!groups.has(base)) groups.set(base, { plural: false, forms: new Map() });
    const g = groups.get(base);
    if (m) {
      g.plural = true;
      g.forms.set(m[1], k);
    } else g.forms.set("", k);
  }
  const entries = [];
  for (const [key, g] of groups) {
    if (g.plural && g.forms.has("")) fail(`${key} is both a plain key and a plural (${key}_…)`);
    if (g.plural && !g.forms.has("other")) fail(`${key}: plural forms need ${key}_other`);
    const cats = g.plural ? PLURAL_ORDER.filter((c) => g.forms.has(c)) : [""];
    const args = [];
    for (const c of cats) for (const name of placeholders(sub(messages[en].get(g.forms.get(c))))) if (!args.includes(name)) args.push(name);
    if (g.plural && !args.includes("count")) args.push("count");
    const texts = {};
    for (const l of LANGUAGES) {
      if (!g.plural) texts[l.source] = sub(messages[l.source].get(g.forms.get("")));
      else {
        const allowed = new Set(["zero", ...l.plurals]);
        texts[l.source] = Object.fromEntries(cats.filter((c) => allowed.has(c)).map((c) => [c, sub(messages[l.source].get(g.forms.get(c)))]));
        if (!texts[l.source].other) fail(`${l.source} ${key}: no "other" form`);
      }
    }
    entries.push({ key, plural: g.plural, args, texts });
  }
  return entries.sort((a, b) => byCodePoint(a.key, b.key));
}

/** i18next text → Apple format string with positional arguments. */
export function toAppleFormat(text, args, { plural = false } = {}) {
  if (!args.length) return text;
  return text.replace(/%/g, "%%").replace(PLACEHOLDER, (_, name) => {
    const n = args.indexOf(name) + 1;
    if (!n) fail(`{{${name}}} has no argument number`);
    return plural && name === "count" ? `%${n}$ld` : `%${n}$@`;
  });
}

// ───────────────────────────── writing ─────────────────────────────

const stringsEscape = (s) =>
  s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n").replace(/\r/g, "\\r").replace(/\t/g, "\\t");
const xmlEscape = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

export function renderStrings(entries, lang) {
  const lines = entries.filter((e) => !e.plural).map((e) => `"${stringsEscape(e.key)}" = "${stringsEscape(toAppleFormat(e.texts[lang], e.args))}";`);
  return `/* ${GENERATED_BY} */\n\n${lines.join("\n")}\n`;
}

export function renderStringsdict(entries, lang) {
  const body = entries
    .filter((e) => e.plural)
    .map((e) => {
      const n = e.args.indexOf("count") + 1;
      const forms = Object.entries(e.texts[lang])
        .map(([cat, text]) => `\t\t\t<key>${cat}</key>\n\t\t\t<string>${xmlEscape(toAppleFormat(text, e.args, { plural: true }))}</string>`)
        .join("\n");
      return `\t<key>${xmlEscape(e.key)}</key>
\t<dict>
\t\t<key>NSStringLocalizedFormatKey</key>
\t\t<string>%${n}$#@count@</string>
\t\t<key>count</key>
\t\t<dict>
\t\t\t<key>NSStringFormatSpecTypeKey</key>
\t\t\t<string>NSStringPluralRuleType</string>
\t\t\t<key>NSStringFormatValueTypeKey</key>
\t\t\t<string>ld</string>
${forms}
\t\t</dict>
\t</dict>`;
    })
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- ${GENERATED_BY} -->
<plist version="1.0">
<dict>
${body}
</dict>
</plist>
`;
}

const swiftString = (s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

export function renderKeysSwift(entries, productName) {
  const all = entries.map((e) => `        ${swiftString(e.key)},`).join("\n");
  const plural = entries.filter((e) => e.plural).map((e) => `        ${swiftString(e.key)},`).join("\n");
  const args = entries
    .filter((e) => e.args.length)
    .map((e) => `        ${swiftString(e.key)}: [${e.args.map(swiftString).join(", ")}],`)
    .join("\n");
  return `// ${GENERATED_BY}
// Sources: apps/desktop/src/i18n/locales/{en,zh-CN}/*.json (keys "<namespace>.<path>") and
// apps/macos/Localization/*.{en,zh-CN}.json (keys "mac.<path>"), with {{product}} = ${swiftString(productName)}.
// Regenerate with \`node apps/macos/scripts/gen-strings.mjs\`; CI runs it with --check.

/// Every key in Localizable.strings and Localizable.stringsdict (en, zh-Hans), for debug-time checks.
///
/// Argument convention, identical in every language:
/// - \`arguments[key]\` lists the i18next placeholder names in order: argument N is \`%N$@\`, so pass Strings.
/// - Keys in \`plural\` live in Localizable.stringsdict; their \`count\` argument is \`%N$ld\`, so pass an Int.
/// - Keys with no entry in \`arguments\` (and not in \`plural\`) are plain text: never run them through
///   \`String(format:)\` (a "%" in them is literal).
nonisolated enum L10nKeys {
    static let all: Set<String> = [
${all}
    ]

    static let plural: Set<String> = [
${plural}
    ]

    static let arguments: [String: [String]] = [
${args}
    ]
}
`;
}

/** Every generated file: [{ path (relative to the repo root), content }]. */
export function generate(root = REPO_ROOT, brand = "default") {
  const shared = loadShared(root);
  const fragments = loadFragments(root);
  const messages = {};
  for (const { source } of LANGUAGES) {
    messages[source] = new Map(shared[source]);
    for (const [k, v] of fragments[source]) messages[source].set(k, v);
  }
  const productName = loadProductName(root, brand);
  const entries = buildCatalog(messages, productName);
  const files = [];
  for (const l of LANGUAGES) {
    const dir = `${PATHS.resources}/${l.apple}.lproj`;
    files.push({ path: `${dir}/Localizable.strings`, content: renderStrings(entries, l.source) });
    files.push({ path: `${dir}/Localizable.stringsdict`, content: renderStringsdict(entries, l.source) });
  }
  files.push({ path: PATHS.keys, content: renderKeysSwift(entries, productName) });
  return { files, entries };
}

export function main(argv = process.argv.slice(2)) {
  const opt = (name) => {
    const i = argv.indexOf(name);
    return i < 0 ? undefined : (argv[i + 1] ?? fail(`${name} needs a value`));
  };
  const known = new Set(["--check", "--root", "--brand"]);
  const bad = argv.find((a, i) => a.startsWith("--") && !known.has(a) && !["--root", "--brand"].includes(argv[i - 1]));
  if (bad) fail(`unknown option ${bad}`);
  const check = argv.includes("--check");
  const root = resolve(opt("--root") ?? REPO_ROOT);
  const { files, entries } = generate(root, opt("--brand") ?? "default");
  const stale = [];
  for (const f of files) {
    const target = join(root, f.path);
    const current = existsSync(target) ? readFileSync(target, "utf8") : undefined;
    if (current === f.content) continue;
    if (check) stale.push(f.path);
    else {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, f.content);
      console.log(`gen-strings: wrote ${f.path}`);
    }
  }
  if (stale.length) {
    console.error(`gen-strings: out of date (run node apps/macos/scripts/gen-strings.mjs):\n${stale.map((p) => `  ${p}`).join("\n")}`);
    return 1;
  }
  const plurals = entries.filter((e) => e.plural).length;
  console.log(`gen-strings: ${entries.length} keys (${plurals} plural) ${check ? "up to date" : "generated"}`);
  return 0;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  try {
    process.exitCode = main();
  } catch (e) {
    console.error(`gen-strings: ${e instanceof StringsError ? e.message : e.stack}`);
    process.exitCode = 2;
  }
}
