#!/usr/bin/env node
// Generate src/api/generated.ts from the Rust facade's JSON Schema.
//
//   pnpm gen:types                      # runs `cargo run -q -p pagelamp-cli -- schema`
//   pnpm gen:types --from schema.json   # uses a schema file instead (no Rust toolchain needed)
//
// The schema is ONE draft-2020-12 document (title "PageLampAppTypes") with every facade type
// under `$defs` (see crates/pagelamp-app/src/lib.rs → `json_schema()`). Never edit
// generated.ts by hand: change the Rust type, then re-run this script.

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const desktopDir = resolve(here, "..");
const repoRoot = resolve(desktopDir, "../..");
const outFile = join(desktopDir, "src/api/generated.ts");

function readSchema() {
  const fromIndex = process.argv.indexOf("--from");
  if (fromIndex !== -1) {
    const file = process.argv[fromIndex + 1];
    if (!file) throw new Error("--from needs a file path");
    return readFileSync(resolve(process.cwd(), file), "utf8");
  }
  // cargo is often not on PATH in GUI-launched shells; rustup installs it here.
  const env = { ...process.env, PATH: `${join(homedir(), ".cargo/bin")}:${process.env.PATH}` };
  return execFileSync("cargo", ["run", "-q", "-p", "pagelamp-cli", "--", "schema"], {
    cwd: repoRoot,
    env,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "inherit"],
    maxBuffer: 16 * 1024 * 1024,
  });
}

const schema = JSON.parse(readSchema());
if (!schema.$defs) throw new Error("expected a schema document with $defs");

const ts = await compile(schema, "PageLampAppTypes", {
  bannerComment: [
    "/* eslint-disable */",
    "// GENERATED by scripts/gen-types.mjs from `pagelamp schema` — DO NOT EDIT.",
    "// Source of truth: crates/pagelamp-app/src/lib.rs, crates/pagelamp-core/src/{model,views}.rs",
  ].join("\n"),
  additionalProperties: false,
  unreachableDefinitions: true,
  // Prettier (bundled with json-schema-to-typescript) formats the output; Biome ignores
  // this file (see biome.json) because it is generated.
  style: { semi: true, printWidth: 100 },
});

writeFileSync(outFile, ts);
console.log(`wrote ${outFile}`);
