#!/usr/bin/env node
// PageLamp design tokens → CSS custom properties (Tauri) + SwiftUI constants (native Mac).
// Spec: docs/design/macos-shell.md §10. Format: W3C DTCG 2025.10 (tokens + resolver).
// Zero dependencies: Node ≥ 24 and node: built-ins only. Output is deterministic.
//
//   node design/tokens/gen-tokens.mjs            write the generated files
//   node design/tokens/gen-tokens.mjs --check    exit 1 if a generated file is missing or stale (CI)
//   options: --root <dir>   repository root to write/check under (default: two levels up)
//
// Inputs:  design/tokens/pagelamp.resolver.json and the *.tokens.json files it references.
// Outputs: apps/macos/Sources/PageLamp/Generated/PLTokens.swift
//          apps/desktop/src/styles/tokens.css   (--pl-* custom properties per resolver context)
//          apps/desktop/src/styles/glass.css    (.pl-glass recipe, spec §8 / §10.5)
// See design/tokens/README.md for the pipeline and the dev.pagelamp $extensions.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const TOKENS_DIR = dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = resolve(TOKENS_DIR, "..", "..");
export const OUTPUTS = Object.freeze({
  swift: "apps/macos/Sources/PageLamp/Generated/PLTokens.swift",
  css: "apps/desktop/src/styles/tokens.css",
  glass: "apps/desktop/src/styles/glass.css",
});
const VENDOR = "dev.pagelamp";
const GENERATED_BY = "Generated by design/tokens/gen-tokens.mjs from design/tokens/*.tokens.json. Do not edit.";

// ───────────────────────────── small helpers ─────────────────────────────

const isObj = (v) => v !== null && typeof v === "object" && !Array.isArray(v);
/** Round to `digits` decimals and print without trailing zeros (no "-0", no exponent). */
export function fmt(x, digits = 4) {
  const f = 10 ** digits;
  const v = Math.round(x * f) / f;
  return String(Object.is(v, -0) ? 0 : v);
}
const fail = (msg) => {
  throw new Error(msg);
};

// ───────────────────────────── colour ─────────────────────────────
// OKLCH → OKLab → linear sRGB with the CSS Color 4 matrices; Display P3 via XYZ D65.

export const srgbEncode = (x) =>
  Math.abs(x) <= 0.0031308 ? 12.92 * x : Math.sign(x) * (1.055 * Math.abs(x) ** (1 / 2.4) - 0.055);
export const srgbDecode = (x) =>
  Math.abs(x) <= 0.04045 ? x / 12.92 : Math.sign(x) * ((Math.abs(x) + 0.055) / 1.055) ** 2.4;

export function oklchToLinearSrgb([L, C, h]) {
  const hr = (h * Math.PI) / 180;
  const a = C * Math.cos(hr);
  const b = C * Math.sin(hr);
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
}

const SRGB_TO_XYZ = [
  [0.41239079926595934, 0.357584339383878, 0.1804807884018343],
  [0.21263900587151027, 0.715168678767756, 0.07219231536073371],
  [0.01933081871559182, 0.11919477979462598, 0.9505321522496607],
];
const XYZ_TO_P3 = [
  [2.4934969119414254, -0.9313836179191239, -0.40271078445071684],
  [-0.8294889695615747, 1.7626640603183463, 0.023624685841943577],
  [0.03584583024378447, -0.07617238926804182, 0.9568845240076872],
];
const mul = (M, v) => M.map((r) => r[0] * v[0] + r[1] * v[1] + r[2] * v[2]);
const clamp01 = (x) => Math.min(1, Math.max(0, x));

/**
 * A DTCG colour value → { srgb (gamma-encoded, clamped 0…1), p3 (encoded, clamped), inGamut, alpha }.
 * "In gamut" means clamping to sRGB moves no channel by half an 8-bit step or more; only colours
 * outside that get Display P3 in Swift.
 */
export function colorToRgb(value) {
  let linear;
  if (value.colorSpace === "oklch") linear = oklchToLinearSrgb(value.components);
  else if (value.colorSpace === "srgb") linear = value.components.map(srgbDecode);
  else fail(`unsupported colorSpace ${value.colorSpace}`);
  const encoded = linear.map(srgbEncode);
  const half = 0.5 / 255;
  const inGamut = encoded.every((x) => x >= -half && x <= 1 + half);
  const p3 = mul(XYZ_TO_P3, mul(SRGB_TO_XYZ, linear)).map(srgbEncode).map(clamp01);
  return { srgb: encoded.map(clamp01), p3, inGamut, alpha: value.alpha ?? 1 };
}

export const hexOf = (rgb) =>
  `#${rgb.map((x) => Math.round(clamp01(x) * 255).toString(16).padStart(2, "0")).join("")}`;

function cssColor(v) {
  const a = v.alpha ?? 1;
  const alpha = a === 1 ? "" : ` / ${fmt(a)}`;
  if (v.colorSpace === "oklch") return `oklch(${v.components.map((x) => fmt(x)).join(" ")}${alpha})`;
  return `rgb(${v.components.map((x) => Math.round(clamp01(x) * 255)).join(" ")}${alpha})`; // 8-bit, like its hex
}

// ───────────────────────────── motion ─────────────────────────────
// SwiftUI Spring(duration:bounce:): mass 1, stiffness (2π/d)², damping 4π(1 − bounce)/d.

export const SPRING_PRESETS = Object.freeze({ smooth: 0, snappy: 0.15, bouncy: 0.3 });
export const SETTLE_EPSILON = 5e-4;

/** The analytic step response x(t) of the spring from 0 to 1. */
export function springCurve(duration, bounce) {
  const w = (2 * Math.PI) / duration;
  const z = 1 - bounce; // damping ratio
  const x = (t) => {
    if (z >= 1) return 1 - (1 + w * t) * Math.exp(-w * t);
    const wd = w * Math.sqrt(1 - z * z);
    return 1 - Math.exp(-z * w * t) * (Math.cos(wd * t) + ((z * w) / wd) * Math.sin(wd * t));
  };
  return { stiffness: w * w, damping: 2 * z * w, x };
}

/** Whole milliseconds after which |x − 1| < 5e-4 for good (checked every 0.1 ms up to 5 s). */
export function settleMs(x) {
  let last = -1;
  for (let i = 0; i <= 50000; i++) if (Math.abs(x(i / 10000) - 1) >= SETTLE_EPSILON) last = i;
  return Math.ceil((last + 1) / 10);
}

/** CSS linear() easing that samples the spring over its settle time. */
export function cssLinear(x, settle, segments = 24) {
  const pts = [];
  for (let i = 0; i <= segments; i++) pts.push(i === segments ? "1" : fmt(x((settle / 1000) * (i / segments))));
  return `linear(${pts.join(", ")})`;
}

/** y of a CSS cubic-bezier at progress u (x1, x2 in [0, 1], so x(s) is monotonic). */
export function bezierAt([x1, y1, x2, y2], u) {
  const bx = (s) => 3 * x1 * s * (1 - s) ** 2 + 3 * x2 * s * s * (1 - s) + s ** 3;
  let lo = 0;
  let hi = 1;
  for (let i = 0; i < 60; i++) {
    const mid = (lo + hi) / 2;
    if (bx(mid) < u) lo = mid;
    else hi = mid;
  }
  const s = (lo + hi) / 2;
  return 3 * y1 * s * (1 - s) ** 2 + 3 * y2 * s * s * (1 - s) + s ** 3;
}

/** Largest |bezier − spring| over the settle time (101 samples of normalised progress). */
export function bezierError(bz, x, settle) {
  let worst = 0;
  for (let i = 0; i <= 100; i++) {
    const u = i / 100;
    worst = Math.max(worst, Math.abs(bezierAt(bz, u) - x((settle / 1000) * u)));
  }
  return worst;
}

/** Deterministic least-squares cubic-bezier fit of a spring (coordinate descent), 3 decimals. */
export function fitBezier(x, settle) {
  const samples = Array.from({ length: 51 }, (_, i) => [i / 50, x((settle / 1000) * (i / 50))]);
  const cost = (p) => samples.reduce((acc, [u, y]) => acc + (bezierAt(p, u) - y) ** 2, 0);
  const bounds = [
    [0, 1],
    [0, 2],
    [0, 1],
    [0, 2],
  ];
  let p = [0.3, 0.6, 0.3, 1];
  let best = cost(p);
  for (let step = 0.1; step >= 1e-4; step /= 2) {
    let improved = true;
    while (improved) {
      improved = false;
      for (let k = 0; k < 4; k++) {
        for (const dir of [1, -1]) {
          const q = p.slice();
          q[k] = Math.min(bounds[k][1], Math.max(bounds[k][0], q[k] + dir * step));
          const c = cost(q);
          if (c < best - 1e-12) {
            p = q;
            best = c;
            improved = true;
          }
        }
      }
    }
  }
  return p.map((v) => Number(fmt(v, 3)));
}

// ───────────────────────────── DTCG loading and resolution ─────────────────────────────

const readJson = (file) => {
  try {
    return JSON.parse(readFileSync(file, "utf8"));
  } catch (e) {
    fail(`${file}: ${e.message}`);
  }
};

/** Loads the resolver document and every token file it references. */
export function loadResolver(dir = TOKENS_DIR) {
  const resolver = readJson(join(dir, "pagelamp.resolver.json"));
  if (resolver.version !== "2025.10") fail(`resolver: version must be "2025.10", got ${resolver.version}`);
  if (!Array.isArray(resolver.resolutionOrder)) fail("resolver: resolutionOrder is required");
  const files = new Map();
  const load = (src) => {
    if (!isObj(src) || typeof src.$ref !== "string" || src.$ref.startsWith("#"))
      fail(`resolver: only file $ref sources are supported, got ${JSON.stringify(src)}`);
    if (!files.has(src.$ref)) files.set(src.$ref, readJson(join(dir, src.$ref)));
    return files.get(src.$ref);
  };
  const modifiers = [];
  for (const entry of resolver.resolutionOrder) {
    const ref = entry.$ref ?? fail(`resolver: inline resolutionOrder entries are not supported`);
    const [, kind, name] = /^#\/(sets|modifiers)\/(.+)$/.exec(ref) ?? fail(`resolver: bad $ref ${ref}`);
    if (kind === "sets") (resolver.sets?.[name] ?? fail(`resolver: no set ${name}`)).sources.forEach(load);
    else {
      const m = resolver.modifiers?.[name] ?? fail(`resolver: no modifier ${name}`);
      const contexts = Object.keys(m.contexts ?? {});
      if (contexts.length < 2) fail(`resolver: modifier ${name} needs two or more contexts`);
      if (!contexts.includes(m.default)) fail(`resolver: modifier ${name} default "${m.default}" is not a context`);
      for (const c of contexts) m.contexts[c].forEach(load);
      modifiers.push({ name, contexts, default: m.default, css: m.$extensions?.[VENDOR]?.css ?? {} });
    }
  }
  return { resolver, files, load, modifiers };
}

const isToken = (node) => isObj(node) && "$value" in node;

/** DTCG merge: groups merge recursively; a token merges shallowly (a context may give only $value). */
function mergeTree(a, b, path = []) {
  const out = { ...a };
  for (const [k, v] of Object.entries(b)) {
    if (k.startsWith("$")) {
      out[k] = v;
      continue;
    }
    const prev = a?.[k];
    if (isToken(v)) {
      if (prev !== undefined && !isToken(prev)) fail(`${[...path, k].join(".")}: a token replaces a group`);
      out[k] = prev ? { ...prev, ...v } : v;
    } else if (isObj(v)) {
      if (isToken(prev)) fail(`${[...path, k].join(".")}: a group replaces a token`);
      out[k] = mergeTree(prev ?? {}, v, [...path, k]);
    } else fail(`${[...path, k].join(".")}: expected a token or group`);
  }
  return out;
}

/** The merged token tree for one permutation, e.g. { theme: "dark", contrast: "more" }. */
export function resolveTree(loaded, input = {}) {
  const { resolver, load } = loaded;
  let tree = {};
  for (const entry of resolver.resolutionOrder) {
    const [, kind, name] = /^#\/(sets|modifiers)\/(.+)$/.exec(entry.$ref);
    if (kind === "sets") {
      for (const src of resolver.sets[name].sources) tree = mergeTree(tree, load(src));
    } else {
      const m = resolver.modifiers[name];
      const ctx = input[name] ?? m.default;
      const sources = m.contexts[ctx] ?? fail(`modifier ${name} has no context "${ctx}"`);
      for (const src of sources) tree = mergeTree(tree, load(src));
    }
  }
  return tree;
}

const INHERITED_EXT = ["css", "macos", "private"];
const TYPES = new Set([
  "color",
  "dimension",
  "number",
  "duration",
  "cubicBezier",
  "fontFamily",
  "fontWeight",
  "typography",
  "shadow",
  "gradient",
  "transition",
]);

/** Flattens a tree into ordered tokens with inherited $type and dev.pagelamp group settings. */
export function flatten(node, path = [], inherited = { type: undefined, ext: {} }) {
  const type = node.$type ?? inherited.type;
  const groupExt = { ...inherited.ext };
  const own = node.$extensions?.[VENDOR] ?? {};
  if (isToken(node)) {
    if (!type) fail(`${path.join(".")}: no $type`);
    if (!TYPES.has(type)) fail(`${path.join(".")}: unsupported $type ${type}`);
    return [{ path, name: path.join("."), type, raw: node.$value, description: node.$description, ext: { ...groupExt, ...own } }];
  }
  for (const k of INHERITED_EXT) if (k in own) groupExt[k] = own[k];
  const out = [];
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith("$")) continue;
    if (/[.{}]/.test(k)) fail(`${[...path, k].join(".")}: names must not contain . { }`);
    if (!isObj(v)) fail(`${[...path, k].join(".")}: expected a token or group`);
    out.push(...flatten(v, [...path, k], { type, ext: groupExt }));
  }
  return out;
}

const ALIAS = /^\{([^{}]+)\}$/;
const aliasOf = (v) => (typeof v === "string" ? ALIAS.exec(v)?.[1] : undefined);

/** Resolves aliases (whole values and sub-values of composites) and validates every token. */
export function resolveTokens(tree) {
  const list = flatten(tree);
  const byName = new Map(list.map((t) => [t.name, t]));
  const resolving = new Set();
  const resolveRef = (name, from, expectType) => {
    const t = byName.get(name) ?? fail(`${from}: alias {${name}} points to no token`);
    if (expectType && t.type !== expectType) fail(`${from}: alias {${name}} is ${t.type}, expected ${expectType}`);
    return valueOf(t);
  };
  const deep = (v, from, type) => {
    const ref = aliasOf(v);
    if (ref) return resolveRef(ref, from, type);
    if (type === "typography") return { ...v, fontFamily: deep(v.fontFamily, from, "fontFamily") };
    if (type === "shadow") return { ...v, color: deep(v.color, from, "color") };
    if (type === "gradient") return v.map((s) => ({ ...s, color: deep(s.color, from, "color") }));
    return v;
  };
  function valueOf(t) {
    if ("value" in t) return t.value;
    if (resolving.has(t.name)) fail(`${t.name}: circular alias`);
    resolving.add(t.name);
    t.value = deep(t.raw, t.name, t.type);
    resolving.delete(t.name);
    validate(t);
    return t.value;
  }
  for (const t of list) valueOf(t);
  return { list: list.filter((t) => !t.ext.private), all: list, byName };
}

const isDim = (d) => isObj(d) && typeof d.value === "number" && (d.unit === "px" || d.unit === "rem");
const isDur = (d) => isObj(d) && typeof d.value === "number" && (d.unit === "ms" || d.unit === "s");
const isBezier = (b) => Array.isArray(b) && b.length === 4 && b.every((n) => typeof n === "number") && b[0] >= 0 && b[0] <= 1 && b[2] >= 0 && b[2] <= 1;

function validateColor(v, where) {
  if (!isObj(v) || !Array.isArray(v.components) || v.components.length !== 3) fail(`${where}: bad colour ${JSON.stringify(v)}`);
  if (v.alpha !== undefined && (v.alpha < 0 || v.alpha > 1)) fail(`${where}: alpha out of range`);
  const { srgb } = colorToRgb(v);
  if (v.hex !== undefined) {
    if (!/^#[0-9a-f]{6}$/i.test(v.hex)) fail(`${where}: hex must be #rrggbb`);
    const want = [1, 3, 5].map((i) => Number.parseInt(v.hex.slice(i, i + 2), 16));
    const got = srgb.map((x) => Math.round(x * 255));
    if (want.some((w, i) => Math.abs(w - got[i]) > 1))
      fail(`${where}: hex ${v.hex} does not match ${v.colorSpace}(${v.components.join(" ")}) = ${hexOf(srgb)}`);
  }
}

function validate(t) {
  const v = t.value;
  const where = t.name;
  switch (t.type) {
    case "color":
      return validateColor(v, where);
    case "dimension":
      return isDim(v) || fail(`${where}: bad dimension`);
    case "duration":
      return isDur(v) || fail(`${where}: bad duration`);
    case "number":
      return typeof v === "number" || fail(`${where}: bad number`);
    case "fontWeight":
      return (typeof v === "number" && v >= 1 && v <= 1000) || fail(`${where}: bad fontWeight`);
    case "cubicBezier":
      return isBezier(v) || fail(`${where}: bad cubicBezier`);
    case "fontFamily":
      return typeof v === "string" || (Array.isArray(v) && v.every((s) => typeof s === "string")) || fail(`${where}: bad fontFamily`);
    case "typography":
      if (!isDim(v.fontSize) || typeof v.fontWeight !== "number" || typeof v.lineHeight !== "number" || !isDim(v.letterSpacing))
        fail(`${where}: bad typography`);
      return;
    case "shadow":
      validateColor(v.color, `${where}.color`);
      for (const k of ["offsetX", "offsetY", "blur", "spread"]) if (!isDim(v[k])) fail(`${where}: bad shadow ${k}`);
      return;
    case "gradient":
      if (!Array.isArray(v) || v.length < 2) fail(`${where}: bad gradient`);
      v.forEach((s, i) => {
        validateColor(s.color, `${where}[${i}]`);
        if (typeof s.position !== "number" || s.position < 0 || s.position > 1) fail(`${where}[${i}]: bad position`);
      });
      return;
    case "transition":
      if (!isDur(v.duration) || !isDur(v.delay) || !isBezier(v.timingFunction)) fail(`${where}: bad transition`);
      return validateMotion(t);
  }
}

const ms = (d) => (d.unit === "s" ? d.value * 1000 : d.value);

export const BEZIER_TOLERANCE = 0.08; // a cubic-bezier cannot follow a bounce closely; CSS uses linear()
const motionChecked = new Map();

/** Springs: the stored derived numbers must match duration + bounce (the source of truth). */
function validateMotion(t) {
  const key = JSON.stringify([t.name, t.value, t.ext.spring, t.ext.curve]);
  if (motionChecked.has(key)) return;
  checkMotion(t);
  motionChecked.set(key, true);
}

function checkMotion(t) {
  const spring = t.ext.spring;
  const curve = t.ext.curve;
  if (!spring && !curve) fail(`${t.name}: a transition needs dev.pagelamp.spring or .curve`);
  if (curve) {
    if (!["easeOut", "easeInOut", "easeIn", "linear"].includes(curve)) fail(`${t.name}: unknown curve ${curve}`);
    return;
  }
  const base = SPRING_PRESETS[spring.preset];
  if (base === undefined) fail(`${t.name}: unknown SwiftUI preset ${spring.preset}`);
  if (spring.bounce !== base) fail(`${t.name}: .${spring.preset} has bounce ${base}, not ${spring.bounce}`);
  const c = springCurve(spring.duration, spring.bounce);
  const settle = settleMs(c.x);
  const want = { stiffness: Number(fmt(c.stiffness, 2)), damping: Number(fmt(c.damping, 2)), settleMs: settle };
  for (const [k, w] of Object.entries(want))
    if (spring[k] !== w) fail(`${t.name}: dev.pagelamp.spring.${k} is ${spring[k]}, the formula gives ${w}`);
  if (ms(t.value.duration) !== settle) fail(`${t.name}: $value.duration must be the settle time ${settle} ms`);
  const err = bezierError(t.value.timingFunction, c.x, settle);
  if (err > BEZIER_TOLERANCE) {
    const fit = fitBezier(c.x, settle);
    fail(`${t.name}: timingFunction is ${fmt(err, 3)} off the spring; the fitted fallback is [${fit.join(", ")}]`);
  }
}

// ───────────────────────────── CSS ─────────────────────────────

export const cssVar = (path) => `--pl-${path.join("-")}`;
const GENERIC_FAMILIES = new Set(["serif", "sans-serif", "monospace", "cursive", "fantasy", "system-ui", "ui-serif", "ui-sans-serif", "ui-monospace", "ui-rounded", "math", "emoji", "fangsong", "-apple-system", "BlinkMacSystemFont"]);
const cssFamily = (v) => (Array.isArray(v) ? v : [v]).map((f) => (GENERIC_FAMILIES.has(f) ? f : `"${f}"`)).join(", ");
const cssDim = (d) => `${fmt(d.value)}${d.unit}`;

/** CSS text for a (sub-)value: a public alias becomes var(--pl-…), a private one its value. */
function cssRef(raw, byName) {
  const ref = aliasOf(raw);
  if (!ref) return undefined;
  const target = byName.get(ref);
  return target.ext.private ? undefined : `var(${cssVar(target.path)})`;
}

/** { "--pl-…": text } for one token in one permutation. */
function cssDecls(t, byName) {
  if (t.ext.css === false) return [];
  const n = cssVar(t.path);
  const ref = cssRef(t.raw, byName);
  const v = t.value;
  switch (t.type) {
    case "color":
      return [[n, ref ?? cssColor(v)]];
    case "dimension":
      return [[n, ref ?? cssDim(v)]];
    case "duration":
      return [[n, ref ?? `${fmt(v.value)}${v.unit}`]];
    case "number":
      return [[n, ref ?? (t.ext.cssUnit === "%" ? `${fmt(v * 100)}%` : fmt(v))]];
    case "fontWeight":
      return [[n, ref ?? fmt(v)]];
    case "cubicBezier":
      return [[n, ref ?? `cubic-bezier(${v.map((x) => fmt(x)).join(", ")})`]];
    case "fontFamily":
      return [[n, ref ?? cssFamily(v)]];
    case "typography": {
      const size = v.fontSize;
      const line = { value: Math.round(v.lineHeight * size.value * 100) / 100, unit: size.unit };
      const family = cssRef(t.raw.fontFamily ?? "", byName) ?? cssFamily(v.fontFamily);
      return [
        [`${n}-size`, cssDim(size)],
        [`${n}-line-height`, cssDim(line)],
        [`${n}-weight`, fmt(v.fontWeight)],
        [n, `${fmt(v.fontWeight)} ${cssDim(size)} / ${cssDim(line)} ${family}`],
      ];
    }
    case "shadow": {
      const color = cssRef(t.raw.color ?? "", byName) ?? cssColor(v.color);
      return [[n, `${v.inset ? "inset " : ""}${cssDim(v.offsetX)} ${cssDim(v.offsetY)} ${cssDim(v.blur)} ${cssDim(v.spread)} ${color}`]];
    }
    case "gradient": {
      const stops = v.map((s, i) => `${cssRef(t.raw[i]?.color ?? "", byName) ?? cssColor(s.color)} ${fmt(s.position * 100)}%`);
      return [[n, `linear-gradient(to bottom, ${stops.join(", ")})`]];
    }
    case "transition": {
      let easing;
      if (t.ext.spring) {
        const { x } = springCurve(t.ext.spring.duration, t.ext.spring.bounce);
        easing = cssLinear(x, t.ext.spring.settleMs);
      } else easing = `cubic-bezier(${v.timingFunction.map((x) => fmt(x)).join(", ")})`;
      return [
        [n, easing],
        [`${n}-duration`, `${fmt(ms(v.duration))}ms`],
      ];
    }
  }
  return [];
}

function cssVarsFor(loaded, input) {
  const { list, byName } = resolveTokens(resolveTree(loaded, input));
  const out = new Map();
  for (const t of list) for (const [k, v] of cssDecls(t, byName)) {
    if (out.has(k)) fail(`CSS variable ${k} is produced twice`);
    out.set(k, v);
  }
  return out;
}

/** All permutations of the modifiers, as arrays of context names in resolver order. */
function combos(modifiers) {
  let out = [[]];
  for (const m of modifiers) out = out.flatMap((c) => m.contexts.map((ctx) => [...c, ctx]));
  return out;
}

/**
 * Rules for tokens.css. Each permutation becomes a `:root<selectors>` block (specificity grows with
 * the number of selectors, and blocks are ordered by it) holding only what the cascade of the
 * blocks before it would get wrong. Contexts with a media query are repeated inside @media with
 * their selector replaced by `:root` (same specificity), so the OS setting works without the
 * attribute. verifyCascade() then checks every attribute × media state against the resolver.
 */
export function buildCssRules(loaded) {
  const mods = loaded.modifiers;
  const all = combos(mods).map((ctxs) => {
    const input = Object.fromEntries(mods.map((m, i) => [m.name, ctxs[i]]));
    const parts = mods.flatMap((m, i) => (ctxs[i] === m.default ? [] : [{ mod: i, sel: m.css[ctxs[i]]?.selector ?? fail(`modifier ${m.name}: context ${ctxs[i]} has no dev.pagelamp.css selector`), media: m.css[ctxs[i]]?.media }]));
    return { ctxs, input, parts, vars: cssVarsFor(loaded, input) };
  });
  const k = (c) => c.parts.length;
  const mediaCount = (c) => c.parts.filter((p) => p.media).length;
  // Within a specificity level: earlier modifiers first (theme, platform, …), then context order.
  const rank = (c, i) => (c.ctxs[i] === mods[i].default ? Number.POSITIVE_INFINITY : mods[i].contexts.indexOf(c.ctxs[i]));
  const lex = (a, b) => {
    for (let i = 0; i < mods.length; i++) {
      const ra = rank(a, i);
      const rb = rank(b, i);
      if (ra !== rb) return ra < rb ? -1 : 1;
    }
    return 0;
  };
  all.sort((a, b) => k(a) - k(b) || mediaCount(a) - mediaCount(b) || lex(a, b));
  const matches = (block, combo) => block.parts.every((p) => combo.ctxs[p.mod] === block.ctxs[p.mod]);
  const baseVars = [...all[0].vars.keys()].sort().join();
  const rules = [];
  for (const c of all) {
    if ([...c.vars.keys()].sort().join() !== baseVars)
      fail(`permutation ${c.ctxs.join("/")} has different tokens than the base set (contexts may only override)`);
    const have = new Map();
    for (const r of rules) if (matches(r, c)) for (const [v, text] of r.decls) have.set(v, text);
    const decls = [...c.vars].filter(([v, text]) => have.get(v) !== text);
    if (decls.length || !rules.length) rules.push({ ctxs: c.ctxs, parts: c.parts, decls, media: [] });
  }
  // @media copies: every non-empty subset of the media-capable modifiers, in resolver order.
  const mediaMods = mods.map((m, i) => i).filter((i) => Object.values(mods[i].css).some((x) => x.media));
  const subsets = [];
  for (let mask = 1; mask < 1 << mediaMods.length; mask++) subsets.push(mediaMods.filter((_, j) => mask & (1 << j)));
  subsets.sort((a, b) => a.length - b.length || a[0] - b[0]);
  const base = rules.slice();
  for (const subset of subsets) {
    for (const r of base) {
      const viaMedia = r.parts.filter((p) => subset.includes(p.mod));
      if (viaMedia.length !== subset.length || viaMedia.some((p) => !p.media)) continue;
      rules.push({ ctxs: r.ctxs, parts: r.parts.map((p) => (subset.includes(p.mod) ? { ...p, viaMedia: true } : p)), decls: r.decls, media: viaMedia.map((p) => p.media) });
    }
  }
  verifyCascade(loaded, all, rules, mediaMods);
  return rules;
}

/** Simulates the browser cascade for every attribute × media state and compares with the resolver. */
function verifyCascade(loaded, all, rules, mediaMods) {
  const mods = loaded.modifiers;
  const byKey = new Map(all.map((c) => [c.ctxs.join("/"), c]));
  for (const attrs of all) {
    for (let mask = 0; mask < 1 << mediaMods.length; mask++) {
      const mediaOn = new Set(mediaMods.filter((_, j) => mask & (1 << j)));
      const effective = attrs.ctxs.map((ctx, i) => {
        if (!mediaOn.has(i)) return ctx;
        const on = Object.entries(mods[i].css).find(([, v]) => v.media)[0];
        return on;
      });
      const want = byKey.get(effective.join("/")).vars;
      const got = new Map();
      const spec = new Map();
      for (const r of rules) {
        const ok = r.parts.every((p) => (p.viaMedia ? mediaOn.has(p.mod) : attrs.ctxs[p.mod] === r.ctxs[p.mod]));
        if (!ok) continue;
        const s = r.parts.length;
        for (const [v, text] of r.decls)
          if (!spec.has(v) || s >= spec.get(v)) {
            spec.set(v, s);
            got.set(v, text);
          }
      }
      for (const [v, text] of want)
        if (got.get(v) !== text)
          fail(`tokens.css cascade is wrong for ${attrs.ctxs.join("/")} (media ${[...mediaOn].map((i) => mods[i].name).join("+") || "none"}): ${v} = ${got.get(v)}, want ${text}`);
    }
  }
}

const CSS_LINE_WIDTH = 100; // apps/desktop/biome.json lineWidth

/** Splits "a, b(c, d), e" at top-level commas. */
function splitTopLevel(text) {
  const out = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i < text.length; i++) {
    if (text[i] === "(") depth++;
    else if (text[i] === ")") depth--;
    else if (text[i] === "," && depth === 0) {
      out.push(text.slice(start, i).trim());
      start = i + 1;
    }
  }
  out.push(text.slice(start).trim());
  return out;
}

/** Index of the ")" that closes the "(" at `open`, or -1. */
function closingParen(text, open) {
  let depth = 0;
  for (let i = open; i < text.length; i++) {
    if (text[i] === "(") depth++;
    else if (text[i] === ")" && --depth === 0) return i;
  }
  return -1;
}

/** One declaration, laid out the way Biome's CSS formatter does (so `biome check` passes). */
function cssDecl(indent, name, value) {
  const line = `${indent}${name}: ${value};`;
  if (line.length <= CSS_LINE_WIDTH) return line;
  const open = value.indexOf("(");
  const isSingleCall = open > 0 && /^[\w-]+$/.test(value.slice(0, open)) && closingParen(value, open) === value.length - 1;
  const args = isSingleCall ? splitTopLevel(value.slice(open + 1, -1)) : [];
  if (args.length < 2) return line;
  return `${indent}${name}: ${value.slice(0, open)}(\n${args.map((a) => `${indent}  ${a}`).join(",\n")}\n${indent});`;
}

function renderCss(loaded) {
  const rules = buildCssRules(loaded);
  const selector = (r) => `:root${r.parts.map((p) => (p.viaMedia ? ":root" : p.sel)).join("")}`;
  const block = (r, indent) =>
    `${indent}${selector(r)} {\n${r.decls.map(([v, t]) => cssDecl(`${indent}  `, v, t)).join("\n")}\n${indent}}`;
  const plain = rules.filter((r) => !r.media.length).map((r) => block(r, ""));
  const groups = new Map();
  for (const r of rules.filter((x) => x.media.length)) {
    const q = r.media.join(" and ");
    if (!groups.has(q)) groups.set(q, []);
    groups.get(q).push(block(r, "  "));
  }
  const media = [...groups].map(([q, blocks]) => `@media ${q} {\n${blocks.join("\n\n")}\n}`);
  const mods = loaded.modifiers
    .map((m) => `${m.name}: ${m.contexts.map((c) => (c === m.default ? `${c} (default)` : `${c} → ${m.css[c].selector}${m.css[c].media ? ` or @media ${m.css[c].media}` : ""}`)).join(", ")}`)
    .map((l) => ` *   ${l}`)
    .join("\n");
  return `/*
 * ${GENERATED_BY}
 * Design tokens for the Tauri app (docs/design/macos-shell.md §8, §10); not imported by the app yet.
 * Resolver contexts on <html>:
${mods}
 */
${[...plain, ...media].join("\n\n")}
`;
}

// glass.css: the functional-layer recipe (spec §8 chrome.css, §10.5), with the token names of §10.
const GLASS_CSS = `/*
 * ${GENERATED_BY}
 * Functional layer only (docs/design/macos-shell.md §8, §10.5): glass never goes on content, rows or
 * anything that scrolls; at most three glass surfaces are visible at once. Needs tokens.css.
 * Never gate on @supports (backdrop-filter: url(#x)): WebKitGTK claims support, then drops the blur.
 */
.pl-glass {
  position: relative;
  isolation: isolate;
  background: var(--pl-color-glass-tint);
  box-shadow:
    inset 0 1px 0 var(--pl-color-glass-rim),
    inset 0 0 0 1px color-mix(in oklab, var(--pl-color-glass-rim) 40%, transparent),
    0 0 0 0.5px var(--pl-color-glass-edge),
    var(--pl-glass-regular-shadow);
}

@supports (backdrop-filter: blur(1px)) or (-webkit-backdrop-filter: blur(1px)) {
  .pl-glass {
    -webkit-backdrop-filter: blur(var(--pl-glass-regular-blur))
      saturate(var(--pl-glass-regular-saturate));
    backdrop-filter: blur(var(--pl-glass-regular-blur)) saturate(var(--pl-glass-regular-saturate));
  }
}

/* Sheen under the text. */
.pl-glass::before {
  content: "";
  position: absolute;
  inset: 0;
  z-index: -1;
  border-radius: inherit;
  pointer-events: none;
  background: var(--pl-glass-regular-sheen);
}

/* glass.interactive: hover raises the tint's opacity, press scales with motion.quick. */
.pl-glass-interactive {
  transition:
    transform var(--pl-motion-quick-duration) var(--pl-motion-quick),
    background-color var(--pl-motion-hover-duration) var(--pl-motion-hover);
}

.pl-glass-interactive:hover {
  background: oklch(
    from var(--pl-color-glass-tint) l c h /
    calc(alpha + var(--pl-glass-interactive-hover-alpha))
  );
}

.pl-glass-interactive:active {
  transform: scale(var(--pl-glass-interactive-press-scale));
}

/* glass.prominent: the one tinted action (solid accent when reduced / increased contrast). */
.pl-glass-prominent {
  background: color-mix(
    in oklab,
    var(--pl-color-accent) var(--pl-glass-prominent-accent-mix),
    transparent
  );
  color: var(--pl-color-on-accent);
}

/* Reduced transparency: opaque surface (tokens.css swaps the tint), no blur, no sheen. */
:root[data-transparency="reduced"] .pl-glass {
  -webkit-backdrop-filter: none;
  backdrop-filter: none;
  background: var(--pl-color-surface-popover);
}

:root[data-transparency="reduced"] .pl-glass::before {
  display: none;
}

@media (prefers-reduced-transparency: reduce) {
  .pl-glass {
    -webkit-backdrop-filter: none;
    backdrop-filter: none;
    background: var(--pl-color-surface-popover);
  }

  .pl-glass::before {
    display: none;
  }
}

/* Increased contrast: opaque surface with a text.primary outline. */
:root[data-contrast="more"] .pl-glass {
  background: var(--pl-color-surface-popover);
  box-shadow: var(--pl-glass-regular-shadow);
  outline: 1px solid var(--pl-color-text-primary);
}

:root[data-contrast="more"] .pl-glass::before {
  display: none;
}

@media (prefers-contrast: more) {
  .pl-glass {
    background: var(--pl-color-surface-popover);
    box-shadow: var(--pl-glass-regular-shadow);
    outline: 1px solid var(--pl-color-text-primary);
  }

  .pl-glass::before {
    display: none;
  }
}

:root[data-transparency="reduced"] .pl-glass-prominent,
:root[data-contrast="more"] .pl-glass-prominent {
  background: var(--pl-color-accent);
}

@media (prefers-reduced-transparency: reduce), (prefers-contrast: more) {
  .pl-glass-prominent {
    background: var(--pl-color-accent);
  }
}

/* Windows contrast themes. */
@media (forced-colors: active) {
  .pl-glass,
  .pl-glass-prominent {
    -webkit-backdrop-filter: none;
    backdrop-filter: none;
    background: Canvas;
    color: CanvasText;
    border: 1px solid CanvasText;
    box-shadow: none;
  }

  .pl-glass::before {
    display: none;
  }
}

@media (prefers-reduced-motion: reduce) {
  .pl-glass-interactive {
    transition: background-color var(--pl-motion-reduced-duration) var(--pl-motion-reduced);
  }

  .pl-glass-interactive:active {
    transform: none;
  }
}

/* The accessory bar dims to 60 % in an inactive window. */
:root[data-window-active="false"] .pl-accessory {
  opacity: 0.6;
}

/* One light (§6.1): the lamp band; a 3 px rule when reduced / increased contrast. */
.pl-lamp-band {
  background: radial-gradient(
    ellipse 70% 120% at 6% 0%,
    var(--pl-color-lamp-wash),
    transparent 75%
  );
}

:root[data-transparency="reduced"] .pl-lamp-band,
:root[data-contrast="more"] .pl-lamp-band {
  background: none;
  box-shadow: inset 3px 0 var(--pl-color-lamp-rule);
}

@media (prefers-reduced-transparency: reduce), (prefers-contrast: more) {
  .pl-lamp-band {
    background: none;
    box-shadow: inset 3px 0 var(--pl-color-lamp-rule);
  }
}

/* Concentric inner shape (§4.4): inner = max(inner-min, outer − padding). */
.pl-concentric {
  border-radius: max(
    var(--pl-radius-inner-min),
    calc(var(--pl-radius-outer, var(--pl-radius-callout)) - var(--pl-pad, var(--pl-space-2)))
  );
}

:lang(zh-CN) .pl-prose {
  line-height: var(--pl-font-cjk-paragraph);
}
`;

// ───────────────────────────── Swift ─────────────────────────────

const SWIFT_ENUMS = Object.freeze({
  color: { enum: "PLColor", doc: "Colours PageLamp draws itself (spec §4.2, §10.1): lamp wash and rule, status glyphs. Everything else uses system colours." },
  radius: { enum: "PLRadius", doc: "PageLamp's own radii (spec §4.4). Windows, sheets, popovers, controls, sidebar and inspector use the system's." },
  space: { enum: "PLSpace", doc: "The 4 pt spacing grid: sN = N × 4 pt.", digitPrefix: "s" },
  layout: { enum: "PLLayout", doc: "Layout measures (spec §10.2)." },
  size: { enum: "PLSize", doc: "Window, column and glyph sizes (spec §10.2)." },
  font: { enum: "PLType", doc: "HIG macOS text styles with their sizes, line heights and weights (spec §4.3, §10.3). macOS has no Dynamic Type; Footnote and Caption are never used." },
  motion: { enum: "PLMotion", doc: "Animations (spec §5, §10.4). Under Reduce Motion use PLMotion.reduced or no animation." },
});
const FORBIDDEN_SWIFT = /(^|\W)(Glass|GlassEffectContainer)(\W|$)/;

const camel = (segments) =>
  segments
    .flatMap((s) => s.split("-"))
    .map((s, i) => (i === 0 ? s : s[0].toUpperCase() + s.slice(1)))
    .join("");

function swiftTarget(t) {
  const override = t.ext.swift;
  if (override === false) return undefined;
  const group = override?.enum ? Object.values(SWIFT_ENUMS).find((g) => g.enum === override.enum) : SWIFT_ENUMS[t.path[0]];
  if (!group) return undefined;
  let name = override?.name ?? camel(t.path.slice(1));
  if (/^\d/.test(name)) name = `${group.digitPrefix ?? "_"}${name}`;
  if (!/^[a-z_][A-Za-z0-9_]*$/.test(name)) fail(`${t.name}: bad Swift name ${name}`);
  return { enum: group.enum, name };
}

const swiftNum = (x) => fmt(x);
const rgbaLiteral = (v) => {
  const c = colorToRgb(v);
  const [r, g, b] = (c.inGamut ? c.srgb : c.p3).map((x) => fmt(x));
  const alpha = fmt(c.alpha);
  return `.${c.inGamut ? "sRGB" : "displayP3"}(${r}, ${g}, ${b}${alpha === "1" ? "" : `, ${alpha}`})`;
};
const SWIFT_WEIGHTS = new Set(["ultraLight", "thin", "light", "regular", "medium", "semibold", "bold", "heavy", "black"]);
const SWIFT_TEXT_STYLES = new Set(["largeTitle", "title", "title2", "title3", "headline", "subheadline", "body", "callout", "footnote", "caption", "caption2"]);
const SWIFT_DESIGNS = new Set(["default", "serif", "rounded", "monospaced"]);

function swiftMember(t, appearances) {
  const mac = t.ext.macos;
  const doc = `    /// \`${t.name}\`${t.description ? ` — ${t.description}` : ""}`;
  const target = swiftTarget(t);
  const decl = (name, rest) => `${doc}\n    static let ${name}${rest}`;
  switch (t.type) {
    case "color": {
      const v = Object.fromEntries(Object.entries(appearances).map(([k, tokens]) => [k, tokens.byName.get(t.name).value]));
      const separate = isObj(mac) && mac.opacity === "separate";
      const opaque = (c) => (separate ? { ...c, alpha: 1 } : c);
      const args = ["light", "dark", "highContrastLight", "highContrastDark"].map((k) => `${k}: ${rgbaLiteral(opaque(v[k]))}`);
      const lines = [decl(target.name, ` = plDynamicColor(\n        ${args.join(",\n        ")}\n    )`)];
      if (separate) {
        lines.push(`    /// Peak opacity of \`${t.name}\` in the light appearance.\n    static let ${target.name}OpacityLight: Double = ${swiftNum(v.light.alpha ?? 1)}`);
        lines.push(`    /// Peak opacity of \`${t.name}\` in the dark appearance.\n    static let ${target.name}OpacityDark: Double = ${swiftNum(v.dark.alpha ?? 1)}`);
      }
      return lines;
    }
    case "dimension":
      return [decl(target.name, `: CGFloat = ${swiftNum(typeof mac === "number" ? mac : t.value.value)}`)];
    case "number":
      if (isObj(mac) && typeof mac.lineSpacing === "number") return [decl(target.name, `: CGFloat = ${swiftNum(mac.lineSpacing)}`)];
      return [decl(target.name, `: Double = ${swiftNum(typeof mac === "number" ? mac : t.value)}`)];
    case "typography": {
      if (!isObj(mac)) fail(`${t.name}: typography needs dev.pagelamp.macos { textStyle, size, lineHeight, weight }`);
      if (!SWIFT_TEXT_STYLES.has(mac.textStyle)) fail(`${t.name}: unknown text style ${mac.textStyle}`);
      if (!SWIFT_WEIGHTS.has(mac.weight)) fail(`${t.name}: unknown weight ${mac.weight}`);
      if (mac.design && !SWIFT_DESIGNS.has(mac.design)) fail(`${t.name}: unknown design ${mac.design}`);
      const design = mac.design ? `.${mac.design}` : "nil";
      return [decl(target.name, ` = Style(textStyle: .${mac.textStyle}, size: ${swiftNum(mac.size)}, lineHeight: ${swiftNum(mac.lineHeight)}, weight: .${mac.weight}, design: ${design})`)];
    }
    case "fontFamily":
      if (isObj(mac) && mac.design) {
        if (!SWIFT_DESIGNS.has(mac.design)) fail(`${t.name}: unknown design ${mac.design}`);
        return [decl(target.name, `: Font.Design = .${mac.design}`)];
      }
      return [];
    case "transition": {
      const s = t.ext.spring;
      if (s) {
        return [
          decl(target.name, `: Animation = .${s.preset}${s.duration === 0.5 ? "" : `(duration: ${swiftNum(s.duration)})`}`),
          // The same spring for Core Animation (motion the render server runs, spec §5).
          `    /// \`${t.name}\` for Core Animation: \`CASpringAnimation(perceptualDuration:bounce:)\`.\n    static let ${target.name}Spring = Spring(duration: ${swiftNum(s.duration)}, bounce: ${swiftNum(s.bounce)})`,
        ];
      }
      return [decl(target.name, `: Animation = .${t.ext.curve}(duration: ${swiftNum(ms(t.value.duration) / 1000)})`)];
    }
  }
  return [];
}

function renderSwift(loaded) {
  const fixed = { platform: "macos", backdrop: "none", transparency: "auto" };
  const appearances = {
    light: resolveTokens(resolveTree(loaded, { ...fixed, theme: "light", contrast: "normal" })),
    dark: resolveTokens(resolveTree(loaded, { ...fixed, theme: "dark", contrast: "normal" })),
    highContrastLight: resolveTokens(resolveTree(loaded, { ...fixed, theme: "light", contrast: "more" })),
    highContrastDark: resolveTokens(resolveTree(loaded, { ...fixed, theme: "dark", contrast: "more" })),
  };
  const members = new Map(Object.values(SWIFT_ENUMS).map((g) => [g.enum, []]));
  const seen = new Set();
  for (const t of appearances.light.list) {
    const mac = t.ext.macos;
    if (mac === "system" || mac === "asset") continue;
    const target = swiftTarget(t);
    if (!target) continue;
    const key = `${target.enum}.${target.name}`;
    if (seen.has(key)) fail(`${t.name}: Swift name ${key} is used twice`);
    seen.add(key);
    members.get(target.enum).push(...swiftMember(t, appearances));
  }
  const before = {
    PLMotion: `    /// A spring token as Core Animation takes it: the SwiftUI spring's perceptual duration and
    /// bounce (\`CASpringAnimation(perceptualDuration:bounce:)\` moves like the SwiftUI spring).
    struct Spring: Sendable {
        let duration: Double
        let bounce: Double
    }`,
    PLType: `    /// A HIG macOS text style with the size, line height and weight PageLamp uses it at.
    struct Style: Sendable {
        let textStyle: Font.TextStyle
        let size: CGFloat
        let lineHeight: CGFloat
        let weight: Font.Weight
        let design: Font.Design?

        /// The SwiftUI font for this style (follows the system text style).
        var font: Font { .system(textStyle, design: design, weight: weight) }
    }`,
  };
  const after = {
    PLRadius: `    /// Concentric inner radius (spec §4.4): \`max(innerMin, outer − padding)\`.
    static func concentric(outer: CGFloat, padding: CGFloat) -> CGFloat {
        max(innerMin, outer - padding)
    }`,
  };
  const enums = Object.values(SWIFT_ENUMS).map((g) => {
    const body = [before[g.enum], ...members.get(g.enum), after[g.enum]].filter(Boolean);
    if (!body.length) fail(`Swift enum ${g.enum} would be empty`);
    return `/// ${g.doc}\nnonisolated enum ${g.enum} {\n${body.join("\n\n")}\n}`;
  });
  const swift = `// ${GENERATED_BY}
// Regenerate with \`node design/tokens/gen-tokens.mjs\`; CI runs it with --check.
// Only what the Mac draws itself; system colours, radii and fonts cover the rest (spec §4.2).
// Glass levels are web-only and nothing here is named Glass (it would shadow SwiftUI.Glass).
// Everything is nonisolated: plain constants, usable from any actor whatever the target's default isolation.

import AppKit
import SwiftUI

${enums.join("\n\n")}

/// One appearance's colour: sRGB, or Display P3 for a token outside sRGB.
nonisolated private struct PLRGBA: Sendable {
    enum Space: Sendable { case sRGB, displayP3 }

    let space: Space
    let red: CGFloat
    let green: CGFloat
    let blue: CGFloat
    let alpha: CGFloat

    static func sRGB(_ red: CGFloat, _ green: CGFloat, _ blue: CGFloat, _ alpha: CGFloat = 1) -> PLRGBA {
        PLRGBA(space: .sRGB, red: red, green: green, blue: blue, alpha: alpha)
    }

    static func displayP3(_ red: CGFloat, _ green: CGFloat, _ blue: CGFloat, _ alpha: CGFloat = 1) -> PLRGBA {
        PLRGBA(space: .displayP3, red: red, green: green, blue: blue, alpha: alpha)
    }

    var nsColor: NSColor {
        switch space {
        case .sRGB: NSColor(srgbRed: red, green: green, blue: blue, alpha: alpha)
        case .displayP3: NSColor(displayP3Red: red, green: green, blue: blue, alpha: alpha)
        }
    }
}

/// A colour that follows the view's appearance, Increase Contrast included (no asset catalog needed).
/// The high-contrast names come first so they win whenever the appearance is a high-contrast one.
/// The provider is @Sendable and nonisolated: AppKit may resolve colours off the main thread, where a
/// closure inferred as MainActor (a target with MainActor default isolation) would trap.
nonisolated private func plDynamicColor(light: PLRGBA, dark: PLRGBA, highContrastLight: PLRGBA, highContrastDark: PLRGBA) -> Color {
    Color(nsColor: NSColor(name: nil) { @Sendable appearance in
        switch appearance.bestMatch(from: [.accessibilityHighContrastAqua, .accessibilityHighContrastDarkAqua, .aqua, .darkAqua]) {
        case .darkAqua?: dark.nsColor
        case .accessibilityHighContrastAqua?: highContrastLight.nsColor
        case .accessibilityHighContrastDarkAqua?: highContrastDark.nsColor
        default: light.nsColor
        }
    })
}
`;
  const offending = swift.split("\n").find((l) => !l.trim().startsWith("//") && FORBIDDEN_SWIFT.test(l));
  if (offending) fail(`PLTokens.swift must not declare anything named Glass: ${offending.trim()}`);
  return swift;
}

// ───────────────────────────── driver ─────────────────────────────

/** Every generated file: [{ path (relative to the repo root), content }]. */
export function generate(dir = TOKENS_DIR) {
  const loaded = loadResolver(dir);
  const css = renderCss(loaded);
  const defined = new Set([...css.matchAll(/^\s*(--pl-[\w-]+):/gm)].map((m) => m[1]));
  const local = new Set(["--pl-radius-outer", "--pl-pad"]); // set by the component, with fallbacks
  for (const [, name] of GLASS_CSS.matchAll(/var\((--pl-[\w-]+)/g))
    if (!defined.has(name) && !local.has(name)) fail(`glass.css uses ${name}, which tokens.css does not define`);
  return [
    { path: OUTPUTS.swift, content: renderSwift(loaded) },
    { path: OUTPUTS.css, content: css },
    { path: OUTPUTS.glass, content: GLASS_CSS },
  ];
}

export function main(argv = process.argv.slice(2)) {
  const check = argv.includes("--check");
  const rootAt = argv.indexOf("--root");
  const root = rootAt >= 0 ? resolve(argv[rootAt + 1] ?? fail("--root needs a directory")) : REPO_ROOT;
  const unknown = argv.filter((a, i) => a.startsWith("--") && !["--check", "--root"].includes(a) && argv[i - 1] !== "--root");
  if (unknown.length) fail(`unknown option ${unknown[0]}`);
  const files = generate();
  const stale = [];
  for (const f of files) {
    const target = join(root, f.path);
    const current = existsSync(target) ? readFileSync(target, "utf8") : undefined;
    if (current === f.content) continue;
    if (check) stale.push(f.path);
    else {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, f.content);
      console.log(`gen-tokens: wrote ${f.path}`);
    }
  }
  if (check && stale.length) {
    console.error(`gen-tokens: out of date (run node design/tokens/gen-tokens.mjs):\n${stale.map((p) => `  ${p}`).join("\n")}`);
    return 1;
  }
  if (check) console.log(`gen-tokens: ${files.length} files up to date`);
  return 0;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  try {
    process.exitCode = main();
  } catch (e) {
    console.error(`gen-tokens: ${e.message}`);
    process.exitCode = 2;
  }
}
